name: "Lisa Anders"
output_dir: "."
navbar:
  title: "Lisa Anders"
  left:
    - text: "Home"
      icon: fa-home
      href: index.html
    - text: "R Projects"
      icon: fa-gear
      menu:
        - text: "Battlebots Brackets"
          href: battlebots.html
        - text: "Medical Explorer"
          href: medicalexplorer.html
        - text: "Farkle Statistics"
          href: farkle.html
        
    - text: "Adventures"
      icon: fa-rocket 
      menu:
        - text: "Rav4 Camper Conversion"
          href: ravmajal.html
        - text: "Map"
          href: map.html

  right:
    - icon: fa-envelope fa-lg
    - icon: fa-facebook-f fa-lg
      href: https://www.facebook.com/LisamaeAnders/
    - icon: fa-github fa-lg
      href: https://github.com/leesahanders
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/lisa-anders-engineer/

theme: jekyll-theme-architect